services:
  e-learn-db:
    container_name: e-learn-db
    env_file:
      - .env      
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  e-learn-backend:
    container_name: e-learn-backend
    env_file:
      - .env      
    image: e-learn-backend
    build:
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
    - .:/app
      - /app/node_modules
    depends_on:
      - e-learn-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pg-admin:
    container_name: pg-admin-app
    env_file:
      - .env      
    image: dpage/pgadmin4:snapshot
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - e-learn-db

volumes:
  postgres_data:
  pgadmin-data:
